sudo: true
language: python
env:
  matrix:
    - LUA=lua-5.1
    - LUA=lua-5.2
    - LUA=lua-5.3
    - LUA=luajit-2.0
    - LUA=luajit-2.1
before_install:
  - pip install hererocks
  - hererocks .venv --verbose --luarocks=^ --${LUA/-/=}
  - source .venv/bin/activate
install:
  - sudo apt-get install slapd
  - luarocks make rockspecs/lualdap/lualdap-dev-1.rockspec
script:
  - LUA=lua tests/run-tests.sh
